### ISSUE TITLE
Maybe change default edit permissions?

### ISSUE THREAD

**Issue by Foretack** [Remahy/forsenwiki#17]
It doesnt feel right to let people directly edit the articles of others. This seems like a recipe for disaster, especially since the website is about forsen.

Perhaps people should be able to *suggest* edits rather than directly apply them?

**Comment by KararTY** [comment]
This is a wikipedia-style project, so all articles should be "freely" editable.

Maybe in the future if I were to implement user namespace articles and allow those to only be modified by the authors.

Btw, miss seeing you in chat. peepoZ
